# ... (début du fichier identique) ...

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # ... (Log in to Docker Hub et Build Docker image restent ici) ...

    - name: Scan dependencies with Trivy FS (requirements.txt)
      uses: aquasecurity/trivy-action@master # Action officielle Trivy
      with:
        scan-type: 'fs' # Type de scan: File System
        security-checks: 'vuln' # Ne scanne que les vulnérabilités
        format: 'table' # Output en format tableau pour lisibilité dans les logs
        output: 'trivy-deps-report.txt' # Output vers un fichier
        # Pour les projets Node.js, ce serait 'package-lock.json', etc.

    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'my-flask-app:latest' # Référence à l'image construite localement
        format: 'table' # Output en format tableau pour lisibilité
        output: 'trivy-image-report.txt' # Output vers un fichier

    # ... (Lint Dockerfile et Lint YAML files restent ici ou peuvent être déplacés) ...